name: First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Welcome message, etc
        run: |
          echo "My first GHA job" 
          ls
          cat README.md
          
      - name: ASCII dragon
        run: cowsay -f dragon "run" >> dragon.txt